enum bookingTypes {
  CHECK_SELECTED_DAYS = "CHECK_SELECTED_DAYS",

  HANDLE_SELECTED_HOUR = "HANDLE_SELECTED_HOUR",

  ADD_HOURS_FOR_BOOKING = "ADD_HOURS_FOR_BOOKING",
  REMOVE_HOURS_FROM_BOOKING = "REMOVE_HOURS_FROM_BOOKING",
}

export default bookingTypes;
