enum filterTypes {
  TOGGLE_FILTER_BUTTON="TOGGLE_FILTER_BUTTON",
  CHANGE_FILTER_PRICE="CHANGE_FILTER_PRICE",
  CHANGE_FILTER_BEDS_ROOMS="CHANGE_FILTER_BEDS_ROOMS",
  CHANGE_FILTER_INPUT_VALUES="CHANGE_FILTER_INPUT_VALUES",
  CLEAR_FILTER="CLEAR_FILTER",
  TOGGLE_CHECKBOXES_LIST="TOGGLE_CHECKBOXES_LIST",
  ADD_FORM_DATA="ADD_FORM_DATA"
}

export default filterTypes;
