enum filterTypes {
  TOGGLE_FILTER_BUTTON="TOGGLE_FILTER_BUTTON",
  CHANGE_FILTER_PRICE="CHANGE_FILTER_PRICE",
  CHANGE_FILTER_BEDS_ROOMS="CHANGE_FILTER_BEDS_ROOMS",
  CHANGE_FILTER_PROPERTY_TYPE="CHANGE_FILTER_PROPERTY_TYPE",
  CHANGE_FILTER_HOUSE_RULES="CHANGE_FILTER_HOUSE_RULES",
  CHANGE_FILTER_AMENITIES="CHANGE_FILTER_AMENITIES",
  CHANGE_FILTER_FACILITIES="CHANGE_FILTER_FACILITIES",
  CHANGE_FILTER_AREAS="CHANGE_FILTER_AREAS",
  CLEAR_FILTER="CLEAR_FILTER",
  TOGGLE_PROPERT_TYPE_INPUTS="TOGGLE_PROPERT_TYPE_INPUTS",
  TOGGLE_HOUSE_RULES_INPUTS="TOGGLE_HOUSE_RULES_INPUTS",
  TOGGLE_AMENITIES_INPUTS="TOGGLE_PROPERT_TYPE_INPUTS",
  TOGGLE_FACILITIES_INPUTS="TOGGLE_FACILITIES_INPUTS",
  TOGGLE_AREAS_INPUTS="TOGGLE_AREAS_INPUTS"
}

export default filterTypes;
