enum mainPageTypes {
  ADD_START_DATE = "ADD_START_DATE",
  ADD_END_DATE = "ADD_END_DATE",
  PROCEED_TO_GUESTS = "PROCEED_TO_GUESTS",
  NUMBER_OF_GUESTS = "NUMBER_OF_GUESTS",
  TOGGLE_CALENDAR = "TOGGLE_CALENDAR",
  TOGGLE_SEARCHING = "TOGGLE_SEARCHING",
  TOGGLE_ANYTIME_OR_CALENDAR= "TOGGLE_ANYTIME_OR_CALENDAR"
}

export default mainPageTypes;
