enum mainPageTypes {
  ADD_START_DATE = "ADD_START_DATE",
  ADD_END_DATE = "ADD_END_DATE",
  PROCEED_TO_GUESTS = "PROCEED_TO_GUESTS",
  NUMBER_OF_GUESTS = "NUMBER_OF_GUESTS",
}

export default mainPageTypes;
