enum propertyTypes {
  GET_ALL_PROPERTIES_START = "GET_ALL_PROPERTIES_START",
  GET_ALL_PROPERTIES_SUCCESS = "GET_ALL_PROPERTIES_SUCCESS",
  GET_ALL_PROPERTIES_FAIL = "GET_ALL_PROPERTIES_FAIL",

  GET_PROPERTIES_WO_LOCKS_START = "GET_PROPERTIES_WO_LOCKS_START",
  GET_PROPERTIES_WO_LOCKS_SUCCESS = "GET_PROPERTIES_WO_LOCKS_SUCCESS",
  GET_PROPERTIES_WO_LOCKS_FAIL = "GET_PROPERTIES_WO_LOCKS_FAIL",

  GET_PROPERTY_START = "GET_PROPERTY_START",
  GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS",
  GET_PROPERTY_FAIL = "GET_PROPERTY_FAIL",

  SELECT_PROPERTY = "SELECT_PROPERTY",
  CLEAR_SELECTED_PROPERTY = "CLEAR_SELECTED_PROPERTY",

  THROW_ERROR = "THROW_ERROR",
  CLEAR_ERROR = "CLEAR_ERROR",

  QUICK_VIEW_PROPERTY = "QUICK_VIEW_PROPERTY",
  PAGINATION_PAGE_SIZE="PAGINATION_PAGE_SIZE",
  PAGINATION_CURRENT_PAGE="PAGINATION_CURRENT_PAGE",
  ADD_ACTIVE_PROPERTY_CORDS="ADD_ACTIVE_PROPERTY_CORDS",
  RESET_PROPERTY_CORDS="RESET_PROPERTY_CORDS",
  ADD_RECENTLY_VIEWED="ADD_RECENTLY_VIEWED",
  AVAILABLE_PROPERTIES="AVAILABLE_PROPERTIES"
}

export default propertyTypes;
