enum propertyTypes {
  GET_ALL_PROPERTIES_START = "GET_ALL_PROPERTIES_START",
  GET_ALL_PROPERTIES_SUCCESS = "GET_ALL_PROPERTIES_SUCCESS",
  GET_ALL_PROPERTIES_FAIL = "GET_ALL_PROPERTIES_FAIL",

  GET_PROPERTY_START = "GET_PROPERTY_START",
  GET_PROPERTY_SUCCESS = "GET_PROPERTY_SUCCESS",
  GET_PROPERTY_FAIL = "GET_PROPERTY_FAIL",
}

export default propertyTypes;
