enum reservationTypes {
  GET_ACTIVE_RESERVATIONS_START = "GET_ACTIVE_RESERVATIONS_START",
  GET_ACTIVE_RESERVATIONS_SUCCESS = "GET_ACTIVE_RESERVATIONS_SUCCESS",
  GET_ACTIVE_RESERVATIONS_FAIL = "GET_ACTIVE_RESERVATIONS_FAIL",

  SELECT_RESERVATION_START = "SELECT_RESERVATION_START",
  SELECT_RESERVATION_SUCCESS = "SELECT_RESERVATION_SUCCESS",
  SELECT_RESERVATION_FAIL = "SELECT_RESERVATION_FAIL",

  UPDATE_CURRENT_LOCK = "UPDATE_CURRENT_LOCK",
  
  CLEAR_ERROR = "CLEAR_ERROR",
}

export default reservationTypes;
