enum userTypes {
  GET_USER_RESERVATIONS_START = "GET_USER_RESERVATIONS_START",
  GET_USER_RESERVATIONS_SUCCESS = "GET_USER_RESERVATIONS_SUCCESS",
  GET_USER_RESERVATIONS_FAIL = "GET_USER_RESERVATIONS_FAIL",
}

export default userTypes;
